<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GSxIxKg' shared service.

return $this->privates['.service_locator.GSxIxKg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pollRepository' => ['privates', 'App\\Repository\\PollRepository', 'getPollRepositoryService.php', true],
], [
    'pollRepository' => 'App\\Repository\\PollRepository',
]);
