<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cin0tmM' shared service.

return $this->privates['.service_locator.cin0tmM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminController::showResults' => ['privates', '.service_locator.GSxIxKg', 'get_ServiceLocator_GSxIxKgService.php', true],
    'App\\Controller\\AnswerController::index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\PollController::actionPoll' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\PollController::showResults' => ['privates', '.service_locator.GSxIxKg', 'get_ServiceLocator_GSxIxKgService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.pWfxOQ_', 'get_ServiceLocator_PWfxOQService.php', true],
    'App\\Controller\\AdminController:showResults' => ['privates', '.service_locator.GSxIxKg', 'get_ServiceLocator_GSxIxKgService.php', true],
    'App\\Controller\\AnswerController:index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\PollController:actionPoll' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\PollController:showResults' => ['privates', '.service_locator.GSxIxKg', 'get_ServiceLocator_GSxIxKgService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.pWfxOQ_', 'get_ServiceLocator_PWfxOQService.php', true],
], [
    'App\\Controller\\AdminController::showResults' => '?',
    'App\\Controller\\AnswerController::index' => '?',
    'App\\Controller\\PollController::actionPoll' => '?',
    'App\\Controller\\PollController::showResults' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\AdminController:showResults' => '?',
    'App\\Controller\\AnswerController:index' => '?',
    'App\\Controller\\PollController:actionPoll' => '?',
    'App\\Controller\\PollController:showResults' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\SecurityController:register' => '?',
]);
