<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTEmykKu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTEmykKu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTEmykKu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTEmykKu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTEmykKu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TEmykKu',
    'container.build_id' => 'ea991fab',
    'container.build_time' => 1574325584,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTEmykKu');
